# Generated by Django 5.1.4 on 2024-12-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('meta_description', models.TextField()),
                ('keywords', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
    ]
