# Generated by Django 4.2.11 on 2024-12-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='keywords',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='meta_description',
            field=models.TextField(null=True),
        ),
    ]
